version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  
  pre_build:
    commands:
      - aws codeartifact login --tool npm --domain "${CODEARTIFACT_DOMAIN}" --repository "${CODEARTIFACT_REPO}" --endpoint-url "${CODEARTIFACT_ENDPOINT}"
      - npm ci --no-fund
      - npx gatsby telemetry --disable
  
  build:
    commands:
      - npx gatsby build

artifacts:
  secondary-artifacts:
    index:
      base-directory: public
      files:
        - 'index.html'
    all:
      base-directory: public
      files:
        - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
    - '.cache/**/*'
    - '/root/.npm/**/*'
