version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  
  pre_build:
    commands:
      - aws codeartifact login --tool npm --duration-seconds 0 --domain "${CODEARTIFACT_DOMAIN}" --repository "${CODEARTIFACT_REPO}" --endpoint-url "${CODEARTIFACT_ENDPOINT}" #--namespace examplecompany
      - npm ci --no-fund
      - npx gatsby info
  build:
    commands:
      - npx gatsby build --no-color
  post_build:
    commands:
      - npm list --parseable --long | awk -F':' '{print $2;}' | uniq | sort > deps.txt

artifacts:
  files:
    - public/page-data/app-data.json
    - deps.txt
  secondary-artifacts:
    index:
      base-directory: public
      files:
        - 'index.html'
    all:
      base-directory: public
      files:
        - '**/*'

cache:
  paths:
    - 'public/**/*'
    - '.cache/**/*'
    - '/root/.npm/**/*'
