version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  
  pre_build:
    commands:
      - aws codeartifact login --tool npm --domain "${CODEARTIFACT_DOMAIN}" --repository "${CODEARTIFACT_REPO}" --endpoint-url "${CODEARTIFACT_ENDPOINT}"
      - npm install
      - npx gatsby telemetry --disable
  
  build:
    commands:
      - npx gatsby build

artifacts:
  base-directory: public
  files:
    - '**/*'
  secondary-artifacts:
    index:
      files:
        - index.html
    all:
      files:
        - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
    - '.cache/**/*'
    - '/root/.npm/**/*'
